apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvn-apps
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: mvn-apps
  template:
    metadata:
      labels:
        app: mvn-apps
    spec:
      containers:
      - image: rabbanidocker/mvn-apps
        name: mvn-apps
        ports:
        - containerPort: 8080
