kind: Service
apiVersion: v1
metadata:
  name: mvn-apps-service
spec:
  selector:
    app: mvn-apps
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30000
  type: LoadBalancer
